id: AD92982E9
title: Prayer to Drukpa Kunley
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:05:54.729899
  last_modified_at: 2022-02-28 23:05:54.729906
